### ISSUE TITLE
哈喽 请问你的mc用户名是什么

### ISSUE THREAD

**Issue by lem0nb** [HanHan233/MC-Serverside-Starter#2]
哈喽 请问你的mc用户名是什么

**Comment by HanHan233** [comment]
由于年龄、资金等原因，我并没有能力购买正版Minecraft，因此我使用的是离线登录，所有获知我的用户名的没有任何意义的

**Comment by lem0nb** [comment]
> 由于年龄、资金等原因，我并没有能力购买正版Minecraft，因此我使用的是离线登录，所有获知我的用户名的没有任何意义的

哦哦qwq
